# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gfdgd_xi/Desktop/dde15/gxde-terminal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gfdgd_xi/Desktop/dde15/gxde-terminal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gfdgd_xi/Desktop/dde15/gxde-terminal/CMakeFiles /home/gfdgd_xi/Desktop/dde15/gxde-terminal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gfdgd_xi/Desktop/dde15/gxde-terminal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gxde-terminal

# Build rule for target.
gxde-terminal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gxde-terminal
.PHONY : gxde-terminal

# fast build rule for target.
gxde-terminal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/build
.PHONY : gxde-terminal/fast

#=============================================================================
# Target rules for targets named af

# Build rule for target.
af: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 af
.PHONY : af

# fast build rule for target.
af/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/af.dir/build.make CMakeFiles/af.dir/build
.PHONY : af/fast

#=============================================================================
# Target rules for targets named am_ET

# Build rule for target.
am_ET: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 am_ET
.PHONY : am_ET

# fast build rule for target.
am_ET/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/am_ET.dir/build.make CMakeFiles/am_ET.dir/build
.PHONY : am_ET/fast

#=============================================================================
# Target rules for targets named ar

# Build rule for target.
ar: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ar
.PHONY : ar

# fast build rule for target.
ar/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ar.dir/build.make CMakeFiles/ar.dir/build
.PHONY : ar/fast

#=============================================================================
# Target rules for targets named ast

# Build rule for target.
ast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ast
.PHONY : ast

# fast build rule for target.
ast/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ast.dir/build.make CMakeFiles/ast.dir/build
.PHONY : ast/fast

#=============================================================================
# Target rules for targets named az

# Build rule for target.
az: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 az
.PHONY : az

# fast build rule for target.
az/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/az.dir/build.make CMakeFiles/az.dir/build
.PHONY : az/fast

#=============================================================================
# Target rules for targets named bg

# Build rule for target.
bg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bg
.PHONY : bg

# fast build rule for target.
bg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bg.dir/build.make CMakeFiles/bg.dir/build
.PHONY : bg/fast

#=============================================================================
# Target rules for targets named bn

# Build rule for target.
bn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn
.PHONY : bn

# fast build rule for target.
bn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn.dir/build.make CMakeFiles/bn.dir/build
.PHONY : bn/fast

#=============================================================================
# Target rules for targets named ca

# Build rule for target.
ca: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ca
.PHONY : ca

# fast build rule for target.
ca/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ca.dir/build.make CMakeFiles/ca.dir/build
.PHONY : ca/fast

#=============================================================================
# Target rules for targets named cs

# Build rule for target.
cs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cs
.PHONY : cs

# fast build rule for target.
cs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cs.dir/build.make CMakeFiles/cs.dir/build
.PHONY : cs/fast

#=============================================================================
# Target rules for targets named da

# Build rule for target.
da: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 da
.PHONY : da

# fast build rule for target.
da/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/da.dir/build.make CMakeFiles/da.dir/build
.PHONY : da/fast

#=============================================================================
# Target rules for targets named de

# Build rule for target.
de: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 de
.PHONY : de

# fast build rule for target.
de/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/de.dir/build.make CMakeFiles/de.dir/build
.PHONY : de/fast

#=============================================================================
# Target rules for targets named el

# Build rule for target.
el: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 el
.PHONY : el

# fast build rule for target.
el/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/el.dir/build.make CMakeFiles/el.dir/build
.PHONY : el/fast

#=============================================================================
# Target rules for targets named en_AU

# Build rule for target.
en_AU: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 en_AU
.PHONY : en_AU

# fast build rule for target.
en_AU/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/en_AU.dir/build.make CMakeFiles/en_AU.dir/build
.PHONY : en_AU/fast

#=============================================================================
# Target rules for targets named eo

# Build rule for target.
eo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eo
.PHONY : eo

# fast build rule for target.
eo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eo.dir/build.make CMakeFiles/eo.dir/build
.PHONY : eo/fast

#=============================================================================
# Target rules for targets named es

# Build rule for target.
es: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 es
.PHONY : es

# fast build rule for target.
es/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/es.dir/build.make CMakeFiles/es.dir/build
.PHONY : es/fast

#=============================================================================
# Target rules for targets named es_419

# Build rule for target.
es_419: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 es_419
.PHONY : es_419

# fast build rule for target.
es_419/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/es_419.dir/build.make CMakeFiles/es_419.dir/build
.PHONY : es_419/fast

#=============================================================================
# Target rules for targets named fa

# Build rule for target.
fa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fa
.PHONY : fa

# fast build rule for target.
fa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fa.dir/build.make CMakeFiles/fa.dir/build
.PHONY : fa/fast

#=============================================================================
# Target rules for targets named fi

# Build rule for target.
fi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fi
.PHONY : fi

# fast build rule for target.
fi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fi.dir/build.make CMakeFiles/fi.dir/build
.PHONY : fi/fast

#=============================================================================
# Target rules for targets named fil

# Build rule for target.
fil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fil
.PHONY : fil

# fast build rule for target.
fil/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fil.dir/build.make CMakeFiles/fil.dir/build
.PHONY : fil/fast

#=============================================================================
# Target rules for targets named fr

# Build rule for target.
fr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fr
.PHONY : fr

# fast build rule for target.
fr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fr.dir/build.make CMakeFiles/fr.dir/build
.PHONY : fr/fast

#=============================================================================
# Target rules for targets named gl_ES

# Build rule for target.
gl_ES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gl_ES
.PHONY : gl_ES

# fast build rule for target.
gl_ES/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gl_ES.dir/build.make CMakeFiles/gl_ES.dir/build
.PHONY : gl_ES/fast

#=============================================================================
# Target rules for targets named he

# Build rule for target.
he: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 he
.PHONY : he

# fast build rule for target.
he/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/he.dir/build.make CMakeFiles/he.dir/build
.PHONY : he/fast

#=============================================================================
# Target rules for targets named hi_IN

# Build rule for target.
hi_IN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hi_IN
.PHONY : hi_IN

# fast build rule for target.
hi_IN/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hi_IN.dir/build.make CMakeFiles/hi_IN.dir/build
.PHONY : hi_IN/fast

#=============================================================================
# Target rules for targets named hr

# Build rule for target.
hr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hr
.PHONY : hr

# fast build rule for target.
hr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hr.dir/build.make CMakeFiles/hr.dir/build
.PHONY : hr/fast

#=============================================================================
# Target rules for targets named hu

# Build rule for target.
hu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hu
.PHONY : hu

# fast build rule for target.
hu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hu.dir/build.make CMakeFiles/hu.dir/build
.PHONY : hu/fast

#=============================================================================
# Target rules for targets named hy

# Build rule for target.
hy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hy
.PHONY : hy

# fast build rule for target.
hy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hy.dir/build.make CMakeFiles/hy.dir/build
.PHONY : hy/fast

#=============================================================================
# Target rules for targets named id

# Build rule for target.
id: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 id
.PHONY : id

# fast build rule for target.
id/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/id.dir/build.make CMakeFiles/id.dir/build
.PHONY : id/fast

#=============================================================================
# Target rules for targets named it

# Build rule for target.
it: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 it
.PHONY : it

# fast build rule for target.
it/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/it.dir/build.make CMakeFiles/it.dir/build
.PHONY : it/fast

#=============================================================================
# Target rules for targets named ja

# Build rule for target.
ja: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ja
.PHONY : ja

# fast build rule for target.
ja/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ja.dir/build.make CMakeFiles/ja.dir/build
.PHONY : ja/fast

#=============================================================================
# Target rules for targets named kn_IN

# Build rule for target.
kn_IN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kn_IN
.PHONY : kn_IN

# fast build rule for target.
kn_IN/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/kn_IN.dir/build.make CMakeFiles/kn_IN.dir/build
.PHONY : kn_IN/fast

#=============================================================================
# Target rules for targets named ko

# Build rule for target.
ko: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ko
.PHONY : ko

# fast build rule for target.
ko/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ko.dir/build.make CMakeFiles/ko.dir/build
.PHONY : ko/fast

#=============================================================================
# Target rules for targets named ku_IQ

# Build rule for target.
ku_IQ: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ku_IQ
.PHONY : ku_IQ

# fast build rule for target.
ku_IQ/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ku_IQ.dir/build.make CMakeFiles/ku_IQ.dir/build
.PHONY : ku_IQ/fast

#=============================================================================
# Target rules for targets named lt

# Build rule for target.
lt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lt
.PHONY : lt

# fast build rule for target.
lt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lt.dir/build.make CMakeFiles/lt.dir/build
.PHONY : lt/fast

#=============================================================================
# Target rules for targets named ml

# Build rule for target.
ml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ml
.PHONY : ml

# fast build rule for target.
ml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ml.dir/build.make CMakeFiles/ml.dir/build
.PHONY : ml/fast

#=============================================================================
# Target rules for targets named mn

# Build rule for target.
mn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mn
.PHONY : mn

# fast build rule for target.
mn/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mn.dir/build.make CMakeFiles/mn.dir/build
.PHONY : mn/fast

#=============================================================================
# Target rules for targets named ms

# Build rule for target.
ms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ms
.PHONY : ms

# fast build rule for target.
ms/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ms.dir/build.make CMakeFiles/ms.dir/build
.PHONY : ms/fast

#=============================================================================
# Target rules for targets named nb

# Build rule for target.
nb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nb
.PHONY : nb

# fast build rule for target.
nb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nb.dir/build.make CMakeFiles/nb.dir/build
.PHONY : nb/fast

#=============================================================================
# Target rules for targets named ne

# Build rule for target.
ne: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ne
.PHONY : ne

# fast build rule for target.
ne/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ne.dir/build.make CMakeFiles/ne.dir/build
.PHONY : ne/fast

#=============================================================================
# Target rules for targets named nl

# Build rule for target.
nl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nl
.PHONY : nl

# fast build rule for target.
nl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nl.dir/build.make CMakeFiles/nl.dir/build
.PHONY : nl/fast

#=============================================================================
# Target rules for targets named pa

# Build rule for target.
pa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pa
.PHONY : pa

# fast build rule for target.
pa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pa.dir/build.make CMakeFiles/pa.dir/build
.PHONY : pa/fast

#=============================================================================
# Target rules for targets named pam

# Build rule for target.
pam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pam
.PHONY : pam

# fast build rule for target.
pam/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pam.dir/build.make CMakeFiles/pam.dir/build
.PHONY : pam/fast

#=============================================================================
# Target rules for targets named pl

# Build rule for target.
pl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pl
.PHONY : pl

# fast build rule for target.
pl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pl.dir/build.make CMakeFiles/pl.dir/build
.PHONY : pl/fast

#=============================================================================
# Target rules for targets named pt

# Build rule for target.
pt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pt
.PHONY : pt

# fast build rule for target.
pt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pt.dir/build.make CMakeFiles/pt.dir/build
.PHONY : pt/fast

#=============================================================================
# Target rules for targets named pt_BR

# Build rule for target.
pt_BR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pt_BR
.PHONY : pt_BR

# fast build rule for target.
pt_BR/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pt_BR.dir/build.make CMakeFiles/pt_BR.dir/build
.PHONY : pt_BR/fast

#=============================================================================
# Target rules for targets named ro

# Build rule for target.
ro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ro
.PHONY : ro

# fast build rule for target.
ro/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ro.dir/build.make CMakeFiles/ro.dir/build
.PHONY : ro/fast

#=============================================================================
# Target rules for targets named ru

# Build rule for target.
ru: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ru
.PHONY : ru

# fast build rule for target.
ru/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ru.dir/build.make CMakeFiles/ru.dir/build
.PHONY : ru/fast

#=============================================================================
# Target rules for targets named sk

# Build rule for target.
sk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sk
.PHONY : sk

# fast build rule for target.
sk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sk.dir/build.make CMakeFiles/sk.dir/build
.PHONY : sk/fast

#=============================================================================
# Target rules for targets named sl

# Build rule for target.
sl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sl
.PHONY : sl

# fast build rule for target.
sl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sl.dir/build.make CMakeFiles/sl.dir/build
.PHONY : sl/fast

#=============================================================================
# Target rules for targets named sq

# Build rule for target.
sq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sq
.PHONY : sq

# fast build rule for target.
sq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sq.dir/build.make CMakeFiles/sq.dir/build
.PHONY : sq/fast

#=============================================================================
# Target rules for targets named sr

# Build rule for target.
sr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sr
.PHONY : sr

# fast build rule for target.
sr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sr.dir/build.make CMakeFiles/sr.dir/build
.PHONY : sr/fast

#=============================================================================
# Target rules for targets named sv

# Build rule for target.
sv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sv
.PHONY : sv

# fast build rule for target.
sv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sv.dir/build.make CMakeFiles/sv.dir/build
.PHONY : sv/fast

#=============================================================================
# Target rules for targets named ta

# Build rule for target.
ta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ta
.PHONY : ta

# fast build rule for target.
ta/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ta.dir/build.make CMakeFiles/ta.dir/build
.PHONY : ta/fast

#=============================================================================
# Target rules for targets named tr

# Build rule for target.
tr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tr
.PHONY : tr

# fast build rule for target.
tr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tr.dir/build.make CMakeFiles/tr.dir/build
.PHONY : tr/fast

#=============================================================================
# Target rules for targets named ug

# Build rule for target.
ug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ug
.PHONY : ug

# fast build rule for target.
ug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ug.dir/build.make CMakeFiles/ug.dir/build
.PHONY : ug/fast

#=============================================================================
# Target rules for targets named uk

# Build rule for target.
uk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uk
.PHONY : uk

# fast build rule for target.
uk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uk.dir/build.make CMakeFiles/uk.dir/build
.PHONY : uk/fast

#=============================================================================
# Target rules for targets named ur

# Build rule for target.
ur: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ur
.PHONY : ur

# fast build rule for target.
ur/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ur.dir/build.make CMakeFiles/ur.dir/build
.PHONY : ur/fast

#=============================================================================
# Target rules for targets named vi

# Build rule for target.
vi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vi
.PHONY : vi

# fast build rule for target.
vi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vi.dir/build.make CMakeFiles/vi.dir/build
.PHONY : vi/fast

#=============================================================================
# Target rules for targets named zh_CN

# Build rule for target.
zh_CN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zh_CN
.PHONY : zh_CN

# fast build rule for target.
zh_CN/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zh_CN.dir/build.make CMakeFiles/zh_CN.dir/build
.PHONY : zh_CN/fast

#=============================================================================
# Target rules for targets named zh_HK

# Build rule for target.
zh_HK: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zh_HK
.PHONY : zh_HK

# fast build rule for target.
zh_HK/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zh_HK.dir/build.make CMakeFiles/zh_HK.dir/build
.PHONY : zh_HK/fast

#=============================================================================
# Target rules for targets named zh_TW

# Build rule for target.
zh_TW: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zh_TW
.PHONY : zh_TW

# fast build rule for target.
zh_TW/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zh_TW.dir/build.make CMakeFiles/zh_TW.dir/build
.PHONY : zh_TW/fast

lib/animation.o: lib/animation.c.o
.PHONY : lib/animation.o

# target to build an object file
lib/animation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/animation.c.o
.PHONY : lib/animation.c.o

lib/animation.i: lib/animation.c.i
.PHONY : lib/animation.i

# target to preprocess a source file
lib/animation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/animation.c.i
.PHONY : lib/animation.c.i

lib/animation.s: lib/animation.c.s
.PHONY : lib/animation.s

# target to generate assembly for a file
lib/animation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/animation.c.s
.PHONY : lib/animation.c.s

lib/config.o: lib/config.c.o
.PHONY : lib/config.o

# target to build an object file
lib/config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/config.c.o
.PHONY : lib/config.c.o

lib/config.i: lib/config.c.i
.PHONY : lib/config.i

# target to preprocess a source file
lib/config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/config.c.i
.PHONY : lib/config.c.i

lib/config.s: lib/config.c.s
.PHONY : lib/config.s

# target to generate assembly for a file
lib/config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/config.c.s
.PHONY : lib/config.c.s

lib/constant.o: lib/constant.c.o
.PHONY : lib/constant.o

# target to build an object file
lib/constant.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/constant.c.o
.PHONY : lib/constant.c.o

lib/constant.i: lib/constant.c.i
.PHONY : lib/constant.i

# target to preprocess a source file
lib/constant.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/constant.c.i
.PHONY : lib/constant.c.i

lib/constant.s: lib/constant.c.s
.PHONY : lib/constant.s

# target to generate assembly for a file
lib/constant.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/constant.c.s
.PHONY : lib/constant.c.s

lib/draw.o: lib/draw.c.o
.PHONY : lib/draw.o

# target to build an object file
lib/draw.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/draw.c.o
.PHONY : lib/draw.c.o

lib/draw.i: lib/draw.c.i
.PHONY : lib/draw.i

# target to preprocess a source file
lib/draw.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/draw.c.i
.PHONY : lib/draw.c.i

lib/draw.s: lib/draw.c.s
.PHONY : lib/draw.s

# target to generate assembly for a file
lib/draw.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/draw.c.s
.PHONY : lib/draw.c.s

lib/font.o: lib/font.c.o
.PHONY : lib/font.o

# target to build an object file
lib/font.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/font.c.o
.PHONY : lib/font.c.o

lib/font.i: lib/font.c.i
.PHONY : lib/font.i

# target to preprocess a source file
lib/font.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/font.c.i
.PHONY : lib/font.c.i

lib/font.s: lib/font.c.s
.PHONY : lib/font.s

# target to generate assembly for a file
lib/font.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/font.c.s
.PHONY : lib/font.c.s

lib/keymap.o: lib/keymap.c.o
.PHONY : lib/keymap.o

# target to build an object file
lib/keymap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/keymap.c.o
.PHONY : lib/keymap.c.o

lib/keymap.i: lib/keymap.c.i
.PHONY : lib/keymap.i

# target to preprocess a source file
lib/keymap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/keymap.c.i
.PHONY : lib/keymap.c.i

lib/keymap.s: lib/keymap.c.s
.PHONY : lib/keymap.s

# target to generate assembly for a file
lib/keymap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/keymap.c.s
.PHONY : lib/keymap.c.s

lib/menu.o: lib/menu.c.o
.PHONY : lib/menu.o

# target to build an object file
lib/menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/menu.c.o
.PHONY : lib/menu.c.o

lib/menu.i: lib/menu.c.i
.PHONY : lib/menu.i

# target to preprocess a source file
lib/menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/menu.c.i
.PHONY : lib/menu.c.i

lib/menu.s: lib/menu.c.s
.PHONY : lib/menu.s

# target to generate assembly for a file
lib/menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/menu.c.s
.PHONY : lib/menu.c.s

lib/utils.o: lib/utils.c.o
.PHONY : lib/utils.o

# target to build an object file
lib/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/utils.c.o
.PHONY : lib/utils.c.o

lib/utils.i: lib/utils.c.i
.PHONY : lib/utils.i

# target to preprocess a source file
lib/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/utils.c.i
.PHONY : lib/utils.c.i

lib/utils.s: lib/utils.c.s
.PHONY : lib/utils.s

# target to generate assembly for a file
lib/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/lib/utils.c.s
.PHONY : lib/utils.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/main.c.s
.PHONY : main.c.s

project_path.o: project_path.c.o
.PHONY : project_path.o

# target to build an object file
project_path.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/project_path.c.o
.PHONY : project_path.c.o

project_path.i: project_path.c.i
.PHONY : project_path.i

# target to preprocess a source file
project_path.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/project_path.c.i
.PHONY : project_path.c.i

project_path.s: project_path.c.s
.PHONY : project_path.s

# target to generate assembly for a file
project_path.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/project_path.c.s
.PHONY : project_path.c.s

widget/about_dialog.o: widget/about_dialog.c.o
.PHONY : widget/about_dialog.o

# target to build an object file
widget/about_dialog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/about_dialog.c.o
.PHONY : widget/about_dialog.c.o

widget/about_dialog.i: widget/about_dialog.c.i
.PHONY : widget/about_dialog.i

# target to preprocess a source file
widget/about_dialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/about_dialog.c.i
.PHONY : widget/about_dialog.c.i

widget/about_dialog.s: widget/about_dialog.c.s
.PHONY : widget/about_dialog.s

# target to generate assembly for a file
widget/about_dialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/about_dialog.c.s
.PHONY : widget/about_dialog.c.s

widget/about_widget.o: widget/about_widget.c.o
.PHONY : widget/about_widget.o

# target to build an object file
widget/about_widget.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/about_widget.c.o
.PHONY : widget/about_widget.c.o

widget/about_widget.i: widget/about_widget.c.i
.PHONY : widget/about_widget.i

# target to preprocess a source file
widget/about_widget.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/about_widget.c.i
.PHONY : widget/about_widget.c.i

widget/about_widget.s: widget/about_widget.c.s
.PHONY : widget/about_widget.s

# target to generate assembly for a file
widget/about_widget.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/about_widget.c.s
.PHONY : widget/about_widget.c.s

widget/add_button.o: widget/add_button.c.o
.PHONY : widget/add_button.o

# target to build an object file
widget/add_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/add_button.c.o
.PHONY : widget/add_button.c.o

widget/add_button.i: widget/add_button.c.i
.PHONY : widget/add_button.i

# target to preprocess a source file
widget/add_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/add_button.c.i
.PHONY : widget/add_button.c.i

widget/add_button.s: widget/add_button.c.s
.PHONY : widget/add_button.s

# target to generate assembly for a file
widget/add_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/add_button.c.s
.PHONY : widget/add_button.c.s

widget/appbar.o: widget/appbar.c.o
.PHONY : widget/appbar.o

# target to build an object file
widget/appbar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/appbar.c.o
.PHONY : widget/appbar.c.o

widget/appbar.i: widget/appbar.c.i
.PHONY : widget/appbar.i

# target to preprocess a source file
widget/appbar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/appbar.c.i
.PHONY : widget/appbar.c.i

widget/appbar.s: widget/appbar.c.s
.PHONY : widget/appbar.s

# target to generate assembly for a file
widget/appbar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/appbar.c.s
.PHONY : widget/appbar.c.s

widget/base_panel.o: widget/base_panel.c.o
.PHONY : widget/base_panel.o

# target to build an object file
widget/base_panel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/base_panel.c.o
.PHONY : widget/base_panel.c.o

widget/base_panel.i: widget/base_panel.c.i
.PHONY : widget/base_panel.i

# target to preprocess a source file
widget/base_panel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/base_panel.c.i
.PHONY : widget/base_panel.c.i

widget/base_panel.s: widget/base_panel.c.s
.PHONY : widget/base_panel.s

# target to generate assembly for a file
widget/base_panel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/base_panel.c.s
.PHONY : widget/base_panel.c.s

widget/check_button.o: widget/check_button.c.o
.PHONY : widget/check_button.o

# target to build an object file
widget/check_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/check_button.c.o
.PHONY : widget/check_button.c.o

widget/check_button.i: widget/check_button.c.i
.PHONY : widget/check_button.i

# target to preprocess a source file
widget/check_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/check_button.c.i
.PHONY : widget/check_button.c.i

widget/check_button.s: widget/check_button.c.s
.PHONY : widget/check_button.s

# target to generate assembly for a file
widget/check_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/check_button.c.s
.PHONY : widget/check_button.c.s

widget/click_event_box.o: widget/click_event_box.c.o
.PHONY : widget/click_event_box.o

# target to build an object file
widget/click_event_box.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/click_event_box.c.o
.PHONY : widget/click_event_box.c.o

widget/click_event_box.i: widget/click_event_box.c.i
.PHONY : widget/click_event_box.i

# target to preprocess a source file
widget/click_event_box.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/click_event_box.c.i
.PHONY : widget/click_event_box.c.i

widget/click_event_box.s: widget/click_event_box.c.s
.PHONY : widget/click_event_box.s

# target to generate assembly for a file
widget/click_event_box.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/click_event_box.c.s
.PHONY : widget/click_event_box.c.s

widget/command_button.o: widget/command_button.c.o
.PHONY : widget/command_button.o

# target to build an object file
widget/command_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_button.c.o
.PHONY : widget/command_button.c.o

widget/command_button.i: widget/command_button.c.i
.PHONY : widget/command_button.i

# target to preprocess a source file
widget/command_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_button.c.i
.PHONY : widget/command_button.c.i

widget/command_button.s: widget/command_button.c.s
.PHONY : widget/command_button.s

# target to generate assembly for a file
widget/command_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_button.c.s
.PHONY : widget/command_button.c.s

widget/command_dialog.o: widget/command_dialog.c.o
.PHONY : widget/command_dialog.o

# target to build an object file
widget/command_dialog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_dialog.c.o
.PHONY : widget/command_dialog.c.o

widget/command_dialog.i: widget/command_dialog.c.i
.PHONY : widget/command_dialog.i

# target to preprocess a source file
widget/command_dialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_dialog.c.i
.PHONY : widget/command_dialog.c.i

widget/command_dialog.s: widget/command_dialog.c.s
.PHONY : widget/command_dialog.s

# target to generate assembly for a file
widget/command_dialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_dialog.c.s
.PHONY : widget/command_dialog.c.s

widget/command_panel.o: widget/command_panel.c.o
.PHONY : widget/command_panel.o

# target to build an object file
widget/command_panel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_panel.c.o
.PHONY : widget/command_panel.c.o

widget/command_panel.i: widget/command_panel.c.i
.PHONY : widget/command_panel.i

# target to preprocess a source file
widget/command_panel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_panel.c.i
.PHONY : widget/command_panel.c.i

widget/command_panel.s: widget/command_panel.c.s
.PHONY : widget/command_panel.s

# target to generate assembly for a file
widget/command_panel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/command_panel.c.s
.PHONY : widget/command_panel.c.s

widget/config_window.o: widget/config_window.c.o
.PHONY : widget/config_window.o

# target to build an object file
widget/config_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/config_window.c.o
.PHONY : widget/config_window.c.o

widget/config_window.i: widget/config_window.c.i
.PHONY : widget/config_window.i

# target to preprocess a source file
widget/config_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/config_window.c.i
.PHONY : widget/config_window.c.i

widget/config_window.s: widget/config_window.c.s
.PHONY : widget/config_window.s

# target to generate assembly for a file
widget/config_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/config_window.c.s
.PHONY : widget/config_window.c.s

widget/confirm_dialog.o: widget/confirm_dialog.c.o
.PHONY : widget/confirm_dialog.o

# target to build an object file
widget/confirm_dialog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/confirm_dialog.c.o
.PHONY : widget/confirm_dialog.c.o

widget/confirm_dialog.i: widget/confirm_dialog.c.i
.PHONY : widget/confirm_dialog.i

# target to preprocess a source file
widget/confirm_dialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/confirm_dialog.c.i
.PHONY : widget/confirm_dialog.c.i

widget/confirm_dialog.s: widget/confirm_dialog.c.s
.PHONY : widget/confirm_dialog.s

# target to generate assembly for a file
widget/confirm_dialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/confirm_dialog.c.s
.PHONY : widget/confirm_dialog.c.s

widget/cursor_toggle_button.o: widget/cursor_toggle_button.c.o
.PHONY : widget/cursor_toggle_button.o

# target to build an object file
widget/cursor_toggle_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/cursor_toggle_button.c.o
.PHONY : widget/cursor_toggle_button.c.o

widget/cursor_toggle_button.i: widget/cursor_toggle_button.c.i
.PHONY : widget/cursor_toggle_button.i

# target to preprocess a source file
widget/cursor_toggle_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/cursor_toggle_button.c.i
.PHONY : widget/cursor_toggle_button.c.i

widget/cursor_toggle_button.s: widget/cursor_toggle_button.c.s
.PHONY : widget/cursor_toggle_button.s

# target to generate assembly for a file
widget/cursor_toggle_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/cursor_toggle_button.c.s
.PHONY : widget/cursor_toggle_button.c.s

widget/dialog.o: widget/dialog.c.o
.PHONY : widget/dialog.o

# target to build an object file
widget/dialog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dialog.c.o
.PHONY : widget/dialog.c.o

widget/dialog.i: widget/dialog.c.i
.PHONY : widget/dialog.i

# target to preprocess a source file
widget/dialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dialog.c.i
.PHONY : widget/dialog.c.i

widget/dialog.s: widget/dialog.c.s
.PHONY : widget/dialog.s

# target to generate assembly for a file
widget/dialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dialog.c.s
.PHONY : widget/dialog.c.s

widget/dialog_button.o: widget/dialog_button.c.o
.PHONY : widget/dialog_button.o

# target to build an object file
widget/dialog_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dialog_button.c.o
.PHONY : widget/dialog_button.c.o

widget/dialog_button.i: widget/dialog_button.c.i
.PHONY : widget/dialog_button.i

# target to preprocess a source file
widget/dialog_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dialog_button.c.i
.PHONY : widget/dialog_button.c.i

widget/dialog_button.s: widget/dialog_button.c.s
.PHONY : widget/dialog_button.s

# target to generate assembly for a file
widget/dialog_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dialog_button.c.s
.PHONY : widget/dialog_button.c.s

widget/dropdown_text_button.o: widget/dropdown_text_button.c.o
.PHONY : widget/dropdown_text_button.o

# target to build an object file
widget/dropdown_text_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dropdown_text_button.c.o
.PHONY : widget/dropdown_text_button.c.o

widget/dropdown_text_button.i: widget/dropdown_text_button.c.i
.PHONY : widget/dropdown_text_button.i

# target to preprocess a source file
widget/dropdown_text_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dropdown_text_button.c.i
.PHONY : widget/dropdown_text_button.c.i

widget/dropdown_text_button.s: widget/dropdown_text_button.c.s
.PHONY : widget/dropdown_text_button.s

# target to generate assembly for a file
widget/dropdown_text_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/dropdown_text_button.c.s
.PHONY : widget/dropdown_text_button.c.s

widget/encoding_button.o: widget/encoding_button.c.o
.PHONY : widget/encoding_button.o

# target to build an object file
widget/encoding_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/encoding_button.c.o
.PHONY : widget/encoding_button.c.o

widget/encoding_button.i: widget/encoding_button.c.i
.PHONY : widget/encoding_button.i

# target to preprocess a source file
widget/encoding_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/encoding_button.c.i
.PHONY : widget/encoding_button.c.i

widget/encoding_button.s: widget/encoding_button.c.s
.PHONY : widget/encoding_button.s

# target to generate assembly for a file
widget/encoding_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/encoding_button.c.s
.PHONY : widget/encoding_button.c.s

widget/encoding_panel.o: widget/encoding_panel.c.o
.PHONY : widget/encoding_panel.o

# target to build an object file
widget/encoding_panel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/encoding_panel.c.o
.PHONY : widget/encoding_panel.c.o

widget/encoding_panel.i: widget/encoding_panel.c.i
.PHONY : widget/encoding_panel.i

# target to preprocess a source file
widget/encoding_panel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/encoding_panel.c.i
.PHONY : widget/encoding_panel.c.i

widget/encoding_panel.s: widget/encoding_panel.c.s
.PHONY : widget/encoding_panel.s

# target to generate assembly for a file
widget/encoding_panel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/encoding_panel.c.s
.PHONY : widget/encoding_panel.c.s

widget/entry.o: widget/entry.c.o
.PHONY : widget/entry.o

# target to build an object file
widget/entry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/entry.c.o
.PHONY : widget/entry.c.o

widget/entry.i: widget/entry.c.i
.PHONY : widget/entry.i

# target to preprocess a source file
widget/entry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/entry.c.i
.PHONY : widget/entry.c.i

widget/entry.s: widget/entry.c.s
.PHONY : widget/entry.s

# target to generate assembly for a file
widget/entry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/entry.c.s
.PHONY : widget/entry.c.s

widget/entry_menu.o: widget/entry_menu.c.o
.PHONY : widget/entry_menu.o

# target to build an object file
widget/entry_menu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/entry_menu.c.o
.PHONY : widget/entry_menu.c.o

widget/entry_menu.i: widget/entry_menu.c.i
.PHONY : widget/entry_menu.i

# target to preprocess a source file
widget/entry_menu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/entry_menu.c.i
.PHONY : widget/entry_menu.c.i

widget/entry_menu.s: widget/entry_menu.c.s
.PHONY : widget/entry_menu.s

# target to generate assembly for a file
widget/entry_menu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/entry_menu.c.s
.PHONY : widget/entry_menu.c.s

widget/file_button.o: widget/file_button.c.o
.PHONY : widget/file_button.o

# target to build an object file
widget/file_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/file_button.c.o
.PHONY : widget/file_button.c.o

widget/file_button.i: widget/file_button.c.i
.PHONY : widget/file_button.i

# target to preprocess a source file
widget/file_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/file_button.c.i
.PHONY : widget/file_button.c.i

widget/file_button.s: widget/file_button.c.s
.PHONY : widget/file_button.s

# target to generate assembly for a file
widget/file_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/file_button.c.s
.PHONY : widget/file_button.c.s

widget/highlight_frame.o: widget/highlight_frame.c.o
.PHONY : widget/highlight_frame.o

# target to build an object file
widget/highlight_frame.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/highlight_frame.c.o
.PHONY : widget/highlight_frame.c.o

widget/highlight_frame.i: widget/highlight_frame.c.i
.PHONY : widget/highlight_frame.i

# target to preprocess a source file
widget/highlight_frame.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/highlight_frame.c.i
.PHONY : widget/highlight_frame.c.i

widget/highlight_frame.s: widget/highlight_frame.c.s
.PHONY : widget/highlight_frame.s

# target to generate assembly for a file
widget/highlight_frame.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/highlight_frame.c.s
.PHONY : widget/highlight_frame.c.s

widget/image_button.o: widget/image_button.c.o
.PHONY : widget/image_button.o

# target to build an object file
widget/image_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/image_button.c.o
.PHONY : widget/image_button.c.o

widget/image_button.i: widget/image_button.c.i
.PHONY : widget/image_button.i

# target to preprocess a source file
widget/image_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/image_button.c.i
.PHONY : widget/image_button.c.i

widget/image_button.s: widget/image_button.c.s
.PHONY : widget/image_button.s

# target to generate assembly for a file
widget/image_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/image_button.c.s
.PHONY : widget/image_button.c.s

widget/link_button.o: widget/link_button.c.o
.PHONY : widget/link_button.o

# target to build an object file
widget/link_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/link_button.c.o
.PHONY : widget/link_button.c.o

widget/link_button.i: widget/link_button.c.i
.PHONY : widget/link_button.i

# target to preprocess a source file
widget/link_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/link_button.c.i
.PHONY : widget/link_button.c.i

widget/link_button.s: widget/link_button.c.s
.PHONY : widget/link_button.s

# target to generate assembly for a file
widget/link_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/link_button.c.s
.PHONY : widget/link_button.c.s

widget/panel_button.o: widget/panel_button.c.o
.PHONY : widget/panel_button.o

# target to build an object file
widget/panel_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/panel_button.c.o
.PHONY : widget/panel_button.c.o

widget/panel_button.i: widget/panel_button.c.i
.PHONY : widget/panel_button.i

# target to preprocess a source file
widget/panel_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/panel_button.c.i
.PHONY : widget/panel_button.c.i

widget/panel_button.s: widget/panel_button.c.s
.PHONY : widget/panel_button.s

# target to generate assembly for a file
widget/panel_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/panel_button.c.s
.PHONY : widget/panel_button.c.s

widget/password_button.o: widget/password_button.c.o
.PHONY : widget/password_button.o

# target to build an object file
widget/password_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/password_button.c.o
.PHONY : widget/password_button.c.o

widget/password_button.i: widget/password_button.c.i
.PHONY : widget/password_button.i

# target to preprocess a source file
widget/password_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/password_button.c.i
.PHONY : widget/password_button.c.i

widget/password_button.s: widget/password_button.c.s
.PHONY : widget/password_button.s

# target to generate assembly for a file
widget/password_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/password_button.c.s
.PHONY : widget/password_button.c.s

widget/preference.o: widget/preference.c.o
.PHONY : widget/preference.o

# target to build an object file
widget/preference.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/preference.c.o
.PHONY : widget/preference.c.o

widget/preference.i: widget/preference.c.i
.PHONY : widget/preference.i

# target to preprocess a source file
widget/preference.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/preference.c.i
.PHONY : widget/preference.c.i

widget/preference.s: widget/preference.c.s
.PHONY : widget/preference.s

# target to generate assembly for a file
widget/preference.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/preference.c.s
.PHONY : widget/preference.c.s

widget/preference_slidebar.o: widget/preference_slidebar.c.o
.PHONY : widget/preference_slidebar.o

# target to build an object file
widget/preference_slidebar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/preference_slidebar.c.o
.PHONY : widget/preference_slidebar.c.o

widget/preference_slidebar.i: widget/preference_slidebar.c.i
.PHONY : widget/preference_slidebar.i

# target to preprocess a source file
widget/preference_slidebar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/preference_slidebar.c.i
.PHONY : widget/preference_slidebar.c.i

widget/preference_slidebar.s: widget/preference_slidebar.c.s
.PHONY : widget/preference_slidebar.s

# target to generate assembly for a file
widget/preference_slidebar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/preference_slidebar.c.s
.PHONY : widget/preference_slidebar.c.s

widget/progressbar.o: widget/progressbar.c.o
.PHONY : widget/progressbar.o

# target to build an object file
widget/progressbar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/progressbar.c.o
.PHONY : widget/progressbar.c.o

widget/progressbar.i: widget/progressbar.c.i
.PHONY : widget/progressbar.i

# target to preprocess a source file
widget/progressbar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/progressbar.c.i
.PHONY : widget/progressbar.c.i

widget/progressbar.s: widget/progressbar.c.s
.PHONY : widget/progressbar.s

# target to generate assembly for a file
widget/progressbar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/progressbar.c.s
.PHONY : widget/progressbar.c.s

widget/quake_window.o: widget/quake_window.c.o
.PHONY : widget/quake_window.o

# target to build an object file
widget/quake_window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/quake_window.c.o
.PHONY : widget/quake_window.c.o

widget/quake_window.i: widget/quake_window.c.i
.PHONY : widget/quake_window.i

# target to preprocess a source file
widget/quake_window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/quake_window.c.i
.PHONY : widget/quake_window.c.i

widget/quake_window.s: widget/quake_window.c.s
.PHONY : widget/quake_window.s

# target to generate assembly for a file
widget/quake_window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/quake_window.c.s
.PHONY : widget/quake_window.c.s

widget/remote_panel.o: widget/remote_panel.c.o
.PHONY : widget/remote_panel.o

# target to build an object file
widget/remote_panel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/remote_panel.c.o
.PHONY : widget/remote_panel.c.o

widget/remote_panel.i: widget/remote_panel.c.i
.PHONY : widget/remote_panel.i

# target to preprocess a source file
widget/remote_panel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/remote_panel.c.i
.PHONY : widget/remote_panel.c.i

widget/remote_panel.s: widget/remote_panel.c.s
.PHONY : widget/remote_panel.s

# target to generate assembly for a file
widget/remote_panel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/remote_panel.c.s
.PHONY : widget/remote_panel.c.s

widget/remote_server_dialog.o: widget/remote_server_dialog.c.o
.PHONY : widget/remote_server_dialog.o

# target to build an object file
widget/remote_server_dialog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/remote_server_dialog.c.o
.PHONY : widget/remote_server_dialog.c.o

widget/remote_server_dialog.i: widget/remote_server_dialog.c.i
.PHONY : widget/remote_server_dialog.i

# target to preprocess a source file
widget/remote_server_dialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/remote_server_dialog.c.i
.PHONY : widget/remote_server_dialog.c.i

widget/remote_server_dialog.s: widget/remote_server_dialog.c.s
.PHONY : widget/remote_server_dialog.s

# target to generate assembly for a file
widget/remote_server_dialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/remote_server_dialog.c.s
.PHONY : widget/remote_server_dialog.c.s

widget/rename_dialog.o: widget/rename_dialog.c.o
.PHONY : widget/rename_dialog.o

# target to build an object file
widget/rename_dialog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/rename_dialog.c.o
.PHONY : widget/rename_dialog.c.o

widget/rename_dialog.i: widget/rename_dialog.c.i
.PHONY : widget/rename_dialog.i

# target to preprocess a source file
widget/rename_dialog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/rename_dialog.c.i
.PHONY : widget/rename_dialog.c.i

widget/rename_dialog.s: widget/rename_dialog.c.s
.PHONY : widget/rename_dialog.s

# target to generate assembly for a file
widget/rename_dialog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/rename_dialog.c.s
.PHONY : widget/rename_dialog.c.s

widget/resize_grip.o: widget/resize_grip.c.o
.PHONY : widget/resize_grip.o

# target to build an object file
widget/resize_grip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/resize_grip.c.o
.PHONY : widget/resize_grip.c.o

widget/resize_grip.i: widget/resize_grip.c.i
.PHONY : widget/resize_grip.i

# target to preprocess a source file
widget/resize_grip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/resize_grip.c.i
.PHONY : widget/resize_grip.c.i

widget/resize_grip.s: widget/resize_grip.c.s
.PHONY : widget/resize_grip.s

# target to generate assembly for a file
widget/resize_grip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/resize_grip.c.s
.PHONY : widget/resize_grip.c.s

widget/search_entry.o: widget/search_entry.c.o
.PHONY : widget/search_entry.o

# target to build an object file
widget/search_entry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/search_entry.c.o
.PHONY : widget/search_entry.c.o

widget/search_entry.i: widget/search_entry.c.i
.PHONY : widget/search_entry.i

# target to preprocess a source file
widget/search_entry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/search_entry.c.i
.PHONY : widget/search_entry.c.i

widget/search_entry.s: widget/search_entry.c.s
.PHONY : widget/search_entry.s

# target to generate assembly for a file
widget/search_entry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/search_entry.c.s
.PHONY : widget/search_entry.c.s

widget/search_panel.o: widget/search_panel.c.o
.PHONY : widget/search_panel.o

# target to build an object file
widget/search_panel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/search_panel.c.o
.PHONY : widget/search_panel.c.o

widget/search_panel.i: widget/search_panel.c.i
.PHONY : widget/search_panel.i

# target to preprocess a source file
widget/search_panel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/search_panel.c.i
.PHONY : widget/search_panel.c.i

widget/search_panel.s: widget/search_panel.c.s
.PHONY : widget/search_panel.s

# target to generate assembly for a file
widget/search_panel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/search_panel.c.s
.PHONY : widget/search_panel.c.s

widget/server_button.o: widget/server_button.c.o
.PHONY : widget/server_button.o

# target to build an object file
widget/server_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/server_button.c.o
.PHONY : widget/server_button.c.o

widget/server_button.i: widget/server_button.c.i
.PHONY : widget/server_button.i

# target to preprocess a source file
widget/server_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/server_button.c.i
.PHONY : widget/server_button.c.i

widget/server_button.s: widget/server_button.c.s
.PHONY : widget/server_button.s

# target to generate assembly for a file
widget/server_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/server_button.c.s
.PHONY : widget/server_button.c.s

widget/server_group_button.o: widget/server_group_button.c.o
.PHONY : widget/server_group_button.o

# target to build an object file
widget/server_group_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/server_group_button.c.o
.PHONY : widget/server_group_button.c.o

widget/server_group_button.i: widget/server_group_button.c.i
.PHONY : widget/server_group_button.i

# target to preprocess a source file
widget/server_group_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/server_group_button.c.i
.PHONY : widget/server_group_button.c.i

widget/server_group_button.s: widget/server_group_button.c.s
.PHONY : widget/server_group_button.s

# target to generate assembly for a file
widget/server_group_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/server_group_button.c.s
.PHONY : widget/server_group_button.c.s

widget/shortcut_entry.o: widget/shortcut_entry.c.o
.PHONY : widget/shortcut_entry.o

# target to build an object file
widget/shortcut_entry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/shortcut_entry.c.o
.PHONY : widget/shortcut_entry.c.o

widget/shortcut_entry.i: widget/shortcut_entry.c.i
.PHONY : widget/shortcut_entry.i

# target to preprocess a source file
widget/shortcut_entry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/shortcut_entry.c.i
.PHONY : widget/shortcut_entry.c.i

widget/shortcut_entry.s: widget/shortcut_entry.c.s
.PHONY : widget/shortcut_entry.s

# target to generate assembly for a file
widget/shortcut_entry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/shortcut_entry.c.s
.PHONY : widget/shortcut_entry.c.s

widget/spinbutton.o: widget/spinbutton.c.o
.PHONY : widget/spinbutton.o

# target to build an object file
widget/spinbutton.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/spinbutton.c.o
.PHONY : widget/spinbutton.c.o

widget/spinbutton.i: widget/spinbutton.c.i
.PHONY : widget/spinbutton.i

# target to preprocess a source file
widget/spinbutton.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/spinbutton.c.i
.PHONY : widget/spinbutton.c.i

widget/spinbutton.s: widget/spinbutton.c.s
.PHONY : widget/spinbutton.s

# target to generate assembly for a file
widget/spinbutton.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/spinbutton.c.s
.PHONY : widget/spinbutton.c.s

widget/split_line.o: widget/split_line.c.o
.PHONY : widget/split_line.o

# target to build an object file
widget/split_line.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/split_line.c.o
.PHONY : widget/split_line.c.o

widget/split_line.i: widget/split_line.c.i
.PHONY : widget/split_line.i

# target to preprocess a source file
widget/split_line.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/split_line.c.i
.PHONY : widget/split_line.c.i

widget/split_line.s: widget/split_line.c.s
.PHONY : widget/split_line.s

# target to generate assembly for a file
widget/split_line.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/split_line.c.s
.PHONY : widget/split_line.c.s

widget/switcher.o: widget/switcher.c.o
.PHONY : widget/switcher.o

# target to build an object file
widget/switcher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/switcher.c.o
.PHONY : widget/switcher.c.o

widget/switcher.i: widget/switcher.c.i
.PHONY : widget/switcher.i

# target to preprocess a source file
widget/switcher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/switcher.c.i
.PHONY : widget/switcher.c.i

widget/switcher.s: widget/switcher.c.s
.PHONY : widget/switcher.s

# target to generate assembly for a file
widget/switcher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/switcher.c.s
.PHONY : widget/switcher.c.s

widget/tabbar.o: widget/tabbar.c.o
.PHONY : widget/tabbar.o

# target to build an object file
widget/tabbar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/tabbar.c.o
.PHONY : widget/tabbar.c.o

widget/tabbar.i: widget/tabbar.c.i
.PHONY : widget/tabbar.i

# target to preprocess a source file
widget/tabbar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/tabbar.c.i
.PHONY : widget/tabbar.c.i

widget/tabbar.s: widget/tabbar.c.s
.PHONY : widget/tabbar.s

# target to generate assembly for a file
widget/tabbar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/tabbar.c.s
.PHONY : widget/tabbar.c.s

widget/terminal.o: widget/terminal.c.o
.PHONY : widget/terminal.o

# target to build an object file
widget/terminal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/terminal.c.o
.PHONY : widget/terminal.c.o

widget/terminal.i: widget/terminal.c.i
.PHONY : widget/terminal.i

# target to preprocess a source file
widget/terminal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/terminal.c.i
.PHONY : widget/terminal.c.i

widget/terminal.s: widget/terminal.c.s
.PHONY : widget/terminal.s

# target to generate assembly for a file
widget/terminal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/terminal.c.s
.PHONY : widget/terminal.c.s

widget/text_button.o: widget/text_button.c.o
.PHONY : widget/text_button.o

# target to build an object file
widget/text_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/text_button.c.o
.PHONY : widget/text_button.c.o

widget/text_button.i: widget/text_button.c.i
.PHONY : widget/text_button.i

# target to preprocess a source file
widget/text_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/text_button.c.i
.PHONY : widget/text_button.c.i

widget/text_button.s: widget/text_button.c.s
.PHONY : widget/text_button.s

# target to generate assembly for a file
widget/text_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/text_button.c.s
.PHONY : widget/text_button.c.s

widget/theme_button.o: widget/theme_button.c.o
.PHONY : widget/theme_button.o

# target to build an object file
widget/theme_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/theme_button.c.o
.PHONY : widget/theme_button.c.o

widget/theme_button.i: widget/theme_button.c.i
.PHONY : widget/theme_button.i

# target to preprocess a source file
widget/theme_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/theme_button.c.i
.PHONY : widget/theme_button.c.i

widget/theme_button.s: widget/theme_button.c.s
.PHONY : widget/theme_button.s

# target to generate assembly for a file
widget/theme_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/theme_button.c.s
.PHONY : widget/theme_button.c.s

widget/theme_panel.o: widget/theme_panel.c.o
.PHONY : widget/theme_panel.o

# target to build an object file
widget/theme_panel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/theme_panel.c.o
.PHONY : widget/theme_panel.c.o

widget/theme_panel.i: widget/theme_panel.c.i
.PHONY : widget/theme_panel.i

# target to preprocess a source file
widget/theme_panel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/theme_panel.c.i
.PHONY : widget/theme_panel.c.i

widget/theme_panel.s: widget/theme_panel.c.s
.PHONY : widget/theme_panel.s

# target to generate assembly for a file
widget/theme_panel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/theme_panel.c.s
.PHONY : widget/theme_panel.c.s

widget/titlebar.o: widget/titlebar.c.o
.PHONY : widget/titlebar.o

# target to build an object file
widget/titlebar.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/titlebar.c.o
.PHONY : widget/titlebar.c.o

widget/titlebar.i: widget/titlebar.c.i
.PHONY : widget/titlebar.i

# target to preprocess a source file
widget/titlebar.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/titlebar.c.i
.PHONY : widget/titlebar.c.i

widget/titlebar.s: widget/titlebar.c.s
.PHONY : widget/titlebar.s

# target to generate assembly for a file
widget/titlebar.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/titlebar.c.s
.PHONY : widget/titlebar.c.s

widget/window.o: widget/window.c.o
.PHONY : widget/window.o

# target to build an object file
widget/window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window.c.o
.PHONY : widget/window.c.o

widget/window.i: widget/window.c.i
.PHONY : widget/window.i

# target to preprocess a source file
widget/window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window.c.i
.PHONY : widget/window.c.i

widget/window.s: widget/window.c.s
.PHONY : widget/window.s

# target to generate assembly for a file
widget/window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window.c.s
.PHONY : widget/window.c.s

widget/window_button.o: widget/window_button.c.o
.PHONY : widget/window_button.o

# target to build an object file
widget/window_button.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window_button.c.o
.PHONY : widget/window_button.c.o

widget/window_button.i: widget/window_button.c.i
.PHONY : widget/window_button.i

# target to preprocess a source file
widget/window_button.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window_button.c.i
.PHONY : widget/window_button.c.i

widget/window_button.s: widget/window_button.c.s
.PHONY : widget/window_button.s

# target to generate assembly for a file
widget/window_button.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window_button.c.s
.PHONY : widget/window_button.c.s

widget/window_event_area.o: widget/window_event_area.c.o
.PHONY : widget/window_event_area.o

# target to build an object file
widget/window_event_area.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window_event_area.c.o
.PHONY : widget/window_event_area.c.o

widget/window_event_area.i: widget/window_event_area.c.i
.PHONY : widget/window_event_area.i

# target to preprocess a source file
widget/window_event_area.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window_event_area.c.i
.PHONY : widget/window_event_area.c.i

widget/window_event_area.s: widget/window_event_area.c.s
.PHONY : widget/window_event_area.s

# target to generate assembly for a file
widget/window_event_area.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/window_event_area.c.s
.PHONY : widget/window_event_area.c.s

widget/workspace.o: widget/workspace.c.o
.PHONY : widget/workspace.o

# target to build an object file
widget/workspace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/workspace.c.o
.PHONY : widget/workspace.c.o

widget/workspace.i: widget/workspace.c.i
.PHONY : widget/workspace.i

# target to preprocess a source file
widget/workspace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/workspace.c.i
.PHONY : widget/workspace.c.i

widget/workspace.s: widget/workspace.c.s
.PHONY : widget/workspace.s

# target to generate assembly for a file
widget/workspace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/workspace.c.s
.PHONY : widget/workspace.c.s

widget/workspace_manager.o: widget/workspace_manager.c.o
.PHONY : widget/workspace_manager.o

# target to build an object file
widget/workspace_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/workspace_manager.c.o
.PHONY : widget/workspace_manager.c.o

widget/workspace_manager.i: widget/workspace_manager.c.i
.PHONY : widget/workspace_manager.i

# target to preprocess a source file
widget/workspace_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/workspace_manager.c.i
.PHONY : widget/workspace_manager.c.i

widget/workspace_manager.s: widget/workspace_manager.c.s
.PHONY : widget/workspace_manager.s

# target to generate assembly for a file
widget/workspace_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gxde-terminal.dir/build.make CMakeFiles/gxde-terminal.dir/widget/workspace_manager.c.s
.PHONY : widget/workspace_manager.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... af"
	@echo "... am_ET"
	@echo "... ar"
	@echo "... ast"
	@echo "... az"
	@echo "... bg"
	@echo "... bn"
	@echo "... ca"
	@echo "... cs"
	@echo "... da"
	@echo "... de"
	@echo "... el"
	@echo "... en_AU"
	@echo "... eo"
	@echo "... es"
	@echo "... es_419"
	@echo "... fa"
	@echo "... fi"
	@echo "... fil"
	@echo "... fr"
	@echo "... gl_ES"
	@echo "... he"
	@echo "... hi_IN"
	@echo "... hr"
	@echo "... hu"
	@echo "... hy"
	@echo "... id"
	@echo "... it"
	@echo "... ja"
	@echo "... kn_IN"
	@echo "... ko"
	@echo "... ku_IQ"
	@echo "... lt"
	@echo "... ml"
	@echo "... mn"
	@echo "... ms"
	@echo "... nb"
	@echo "... ne"
	@echo "... nl"
	@echo "... pa"
	@echo "... pam"
	@echo "... pl"
	@echo "... pt"
	@echo "... pt_BR"
	@echo "... ro"
	@echo "... ru"
	@echo "... sk"
	@echo "... sl"
	@echo "... sq"
	@echo "... sr"
	@echo "... sv"
	@echo "... ta"
	@echo "... tr"
	@echo "... ug"
	@echo "... uk"
	@echo "... ur"
	@echo "... vi"
	@echo "... zh_CN"
	@echo "... zh_HK"
	@echo "... zh_TW"
	@echo "... gxde-terminal"
	@echo "... lib/animation.o"
	@echo "... lib/animation.i"
	@echo "... lib/animation.s"
	@echo "... lib/config.o"
	@echo "... lib/config.i"
	@echo "... lib/config.s"
	@echo "... lib/constant.o"
	@echo "... lib/constant.i"
	@echo "... lib/constant.s"
	@echo "... lib/draw.o"
	@echo "... lib/draw.i"
	@echo "... lib/draw.s"
	@echo "... lib/font.o"
	@echo "... lib/font.i"
	@echo "... lib/font.s"
	@echo "... lib/keymap.o"
	@echo "... lib/keymap.i"
	@echo "... lib/keymap.s"
	@echo "... lib/menu.o"
	@echo "... lib/menu.i"
	@echo "... lib/menu.s"
	@echo "... lib/utils.o"
	@echo "... lib/utils.i"
	@echo "... lib/utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... project_path.o"
	@echo "... project_path.i"
	@echo "... project_path.s"
	@echo "... widget/about_dialog.o"
	@echo "... widget/about_dialog.i"
	@echo "... widget/about_dialog.s"
	@echo "... widget/about_widget.o"
	@echo "... widget/about_widget.i"
	@echo "... widget/about_widget.s"
	@echo "... widget/add_button.o"
	@echo "... widget/add_button.i"
	@echo "... widget/add_button.s"
	@echo "... widget/appbar.o"
	@echo "... widget/appbar.i"
	@echo "... widget/appbar.s"
	@echo "... widget/base_panel.o"
	@echo "... widget/base_panel.i"
	@echo "... widget/base_panel.s"
	@echo "... widget/check_button.o"
	@echo "... widget/check_button.i"
	@echo "... widget/check_button.s"
	@echo "... widget/click_event_box.o"
	@echo "... widget/click_event_box.i"
	@echo "... widget/click_event_box.s"
	@echo "... widget/command_button.o"
	@echo "... widget/command_button.i"
	@echo "... widget/command_button.s"
	@echo "... widget/command_dialog.o"
	@echo "... widget/command_dialog.i"
	@echo "... widget/command_dialog.s"
	@echo "... widget/command_panel.o"
	@echo "... widget/command_panel.i"
	@echo "... widget/command_panel.s"
	@echo "... widget/config_window.o"
	@echo "... widget/config_window.i"
	@echo "... widget/config_window.s"
	@echo "... widget/confirm_dialog.o"
	@echo "... widget/confirm_dialog.i"
	@echo "... widget/confirm_dialog.s"
	@echo "... widget/cursor_toggle_button.o"
	@echo "... widget/cursor_toggle_button.i"
	@echo "... widget/cursor_toggle_button.s"
	@echo "... widget/dialog.o"
	@echo "... widget/dialog.i"
	@echo "... widget/dialog.s"
	@echo "... widget/dialog_button.o"
	@echo "... widget/dialog_button.i"
	@echo "... widget/dialog_button.s"
	@echo "... widget/dropdown_text_button.o"
	@echo "... widget/dropdown_text_button.i"
	@echo "... widget/dropdown_text_button.s"
	@echo "... widget/encoding_button.o"
	@echo "... widget/encoding_button.i"
	@echo "... widget/encoding_button.s"
	@echo "... widget/encoding_panel.o"
	@echo "... widget/encoding_panel.i"
	@echo "... widget/encoding_panel.s"
	@echo "... widget/entry.o"
	@echo "... widget/entry.i"
	@echo "... widget/entry.s"
	@echo "... widget/entry_menu.o"
	@echo "... widget/entry_menu.i"
	@echo "... widget/entry_menu.s"
	@echo "... widget/file_button.o"
	@echo "... widget/file_button.i"
	@echo "... widget/file_button.s"
	@echo "... widget/highlight_frame.o"
	@echo "... widget/highlight_frame.i"
	@echo "... widget/highlight_frame.s"
	@echo "... widget/image_button.o"
	@echo "... widget/image_button.i"
	@echo "... widget/image_button.s"
	@echo "... widget/link_button.o"
	@echo "... widget/link_button.i"
	@echo "... widget/link_button.s"
	@echo "... widget/panel_button.o"
	@echo "... widget/panel_button.i"
	@echo "... widget/panel_button.s"
	@echo "... widget/password_button.o"
	@echo "... widget/password_button.i"
	@echo "... widget/password_button.s"
	@echo "... widget/preference.o"
	@echo "... widget/preference.i"
	@echo "... widget/preference.s"
	@echo "... widget/preference_slidebar.o"
	@echo "... widget/preference_slidebar.i"
	@echo "... widget/preference_slidebar.s"
	@echo "... widget/progressbar.o"
	@echo "... widget/progressbar.i"
	@echo "... widget/progressbar.s"
	@echo "... widget/quake_window.o"
	@echo "... widget/quake_window.i"
	@echo "... widget/quake_window.s"
	@echo "... widget/remote_panel.o"
	@echo "... widget/remote_panel.i"
	@echo "... widget/remote_panel.s"
	@echo "... widget/remote_server_dialog.o"
	@echo "... widget/remote_server_dialog.i"
	@echo "... widget/remote_server_dialog.s"
	@echo "... widget/rename_dialog.o"
	@echo "... widget/rename_dialog.i"
	@echo "... widget/rename_dialog.s"
	@echo "... widget/resize_grip.o"
	@echo "... widget/resize_grip.i"
	@echo "... widget/resize_grip.s"
	@echo "... widget/search_entry.o"
	@echo "... widget/search_entry.i"
	@echo "... widget/search_entry.s"
	@echo "... widget/search_panel.o"
	@echo "... widget/search_panel.i"
	@echo "... widget/search_panel.s"
	@echo "... widget/server_button.o"
	@echo "... widget/server_button.i"
	@echo "... widget/server_button.s"
	@echo "... widget/server_group_button.o"
	@echo "... widget/server_group_button.i"
	@echo "... widget/server_group_button.s"
	@echo "... widget/shortcut_entry.o"
	@echo "... widget/shortcut_entry.i"
	@echo "... widget/shortcut_entry.s"
	@echo "... widget/spinbutton.o"
	@echo "... widget/spinbutton.i"
	@echo "... widget/spinbutton.s"
	@echo "... widget/split_line.o"
	@echo "... widget/split_line.i"
	@echo "... widget/split_line.s"
	@echo "... widget/switcher.o"
	@echo "... widget/switcher.i"
	@echo "... widget/switcher.s"
	@echo "... widget/tabbar.o"
	@echo "... widget/tabbar.i"
	@echo "... widget/tabbar.s"
	@echo "... widget/terminal.o"
	@echo "... widget/terminal.i"
	@echo "... widget/terminal.s"
	@echo "... widget/text_button.o"
	@echo "... widget/text_button.i"
	@echo "... widget/text_button.s"
	@echo "... widget/theme_button.o"
	@echo "... widget/theme_button.i"
	@echo "... widget/theme_button.s"
	@echo "... widget/theme_panel.o"
	@echo "... widget/theme_panel.i"
	@echo "... widget/theme_panel.s"
	@echo "... widget/titlebar.o"
	@echo "... widget/titlebar.i"
	@echo "... widget/titlebar.s"
	@echo "... widget/window.o"
	@echo "... widget/window.i"
	@echo "... widget/window.s"
	@echo "... widget/window_button.o"
	@echo "... widget/window_button.i"
	@echo "... widget/window_button.s"
	@echo "... widget/window_event_area.o"
	@echo "... widget/window_event_area.i"
	@echo "... widget/window_event_area.s"
	@echo "... widget/workspace.o"
	@echo "... widget/workspace.i"
	@echo "... widget/workspace.s"
	@echo "... widget/workspace_manager.o"
	@echo "... widget/workspace_manager.i"
	@echo "... widget/workspace_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

